[package]
name = "rp2040_blinky"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
critical-section = "1.2.0"
embedded-hal = "1.0.0"
heapless = "0.9.2"
log = "0.4.29"
panic-halt = "1.0.0"
pms7003-rs = { version = "0.1.0", path = "../pms7003-rs" }
rp2040-boot2 = "0.3.0"
rp2040-hal = { version = "0.12.0", features = ["critical-section-impl"] }
usb-device = "0.3.2"
usbd-serial = "0.2.2"

[profile.release]
lto = true
opt-level = "z"

[[bin]]
name = "rp2040_blinky"
path = "src/main.rs"
test = false
doctest = false
bench = false
